@url = https://fuzzy-space-orbit-xxxxpxj49x5hvjr7-8080.app.github.dev/aluno

POST  {{url}}
Content-Type: application/json

{
    "nome": "Adriano",
    "idade":21
}

###
Get {{url}}

###
PUT {{url}}/3
Content-Type: application/json

{
    "nome": "Giovanna",
    "idade": 22
}

###
DELETE {{url}}/5

###
GET {{url}}/4